services:
  web:
    build: ./djangobnb_backend
    entrypoint: sh /usr/src/djangobnb_backend/entrypoint.sh
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=POSTGRESUSER
      - POSTGRES_PASSWORD=POSTGRESPASSWORD
      - POSTGRES_DB=djangobnb

volumes:
  postgres_data: